import { NextResponse } from "next/server";

export async function GET() {
  const products = [
    {
      id: 1,
      title: "HAVIT HV-G92 Gamepad",
      image: "/Game.png",
      price: 120,
      oldPrice: 160,
      discount: 40,
      rating: 4.5,
      reviews: 88,
    },
    {
      id: 2,
      title: "AK-900 Wired Keyboard",
      image: "/keyboard.png",
      price: 960,
      oldPrice: 1160,
      discount: 35,
      rating: 4,
      reviews: 75,
    },
    {
      id: 3,
      title: "IPS LCD Gaming Monitor",
      image: "/chair.png",
      price: 960,
      oldPrice: 1160,
      discount: 35,
      rating: 4,
      reviews: 99,
    },
    {
      id: 4,
      title: "S-Series Comfort Chair",
      image: "/dragon.png",
      price: 960,
      oldPrice: 1160,
      discount: 35,
      rating: 4,
      reviews: 99,
    },
    {
      id: 5,
      title: "S-Series Comfort Chair",
      image: "/chair.png",
      price: 960,
      oldPrice: 1160,
      discount: 35,
      rating: 4,
      reviews: 75,
    },
    // ======= Without discount =====
    {
      id: 6,
      title: "The north coat",
      image: "/jaket.png",
      price: 260,
      oldPrice: 360,
      rating: 4,
      reviews: 65,
    },
    {
      id: 7,
      title: "Gucci duffle bag",
      image: "/Savoy-medium-duffle-bag.png",
      price: 960,
      oldPrice: 1160,
      rating: 4,
      reviews: 65,
    },
    {
      id: 8,
      title: "RGB liquid CPU Cooler",
      image: "/gammaxx.png",
      price: 160,
      oldPrice: 170,
      rating: 4.5,
      reviews: 65,
    },
    {
      id: 9,
      title: "Small BookSelf",
      image: "/Table.png",
      price: 360,
      // oldPrice: 1160,
      rating: 5,
      reviews: 65,
    },
    // ====== Explore Products ======
    {
      id: 10,
      title: "Breed Dry Dog Food",
      image: "/Dog-Food.png",
      price: 100,
      rating: 3,
      reviews: 35,
    },
    {
      id: 11,
      title: "CANON EOS DSLR Camera",
      image: "/DSLR-Camera.png",
      price: 360,
      rating: 4,
      reviews: 95,
    },
    {
      id: 12,
      title: "ASUS FHD Gaming Laptop",
      image: "/Gaming-Laptop.png",
      price: 700,
      rating: 5,
      reviews: 325,
    },
    {
      id: 13,
      title: "Curology Product Set ",
      image: "/curology.png",
      price: 500,
      rating: 4,
      reviews: 145,
    },
    {
      id: 14,
      title: "Kids Electric Car",
      image: {
        black: "/Electric-Toy-Car.png",
        red: "/Game.png",
      },
      colors: ["black", "red"],
      condition: "New",
      price: 960,
      rating: 5,
      reviews: 65,
    },
    {
      id: 15,
      title: "Jr. Zoom Soccer Cleats",
      image: {
        black: "/Zoom-Soccer.png",
        red: "/Game.png",
      },
      colors: ["black", "red"],
      price: 1160,
      rating: 5,
      reviews: 35,
    },
    {
      id: 16,
      title: "GP11 Shooter USB Gamepad",
      image: {
        black: "/USB-Gamepad.png",
        red: "/Game.png",
      },
      colors: ["black", "red"],
      condition: "New",
      price: 660,
      rating: 4.5,
      reviews: 55,
    },
    {
      id: 17,
      title: "Quilted Satin Jacket",
      image: {
        black: "/Quilted-satin-jacket.png",
        red: "/Game.png",
      },
      colors: ["black", "red"],
      price: 660,
      rating: 4.5,
      reviews: 55,
    },
  ];

  return NextResponse.json(products);
}
